version: '3.9'

x-mutagen:
  sync:
    code:
      alpha: "."
      beta: "volume://code"
      mode: "two-way-resolved"
      ignore:
        vcs: true

services:
  new-world-front-app:
    container_name: new-world-front-app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    networks:
      - default
      - docker_default
    volumes:
      - code:/code
      - node-modules:/code/node_modules
    stdin_open: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.new-world-front.loadbalancer.server.port=8080"
      - "traefik.http.routers.new-world-front.rule=HostRegexp(`nw.localhost`) && (
          Path(
            `/`,
            `/__vite_ping`,
            `/login`,
            `/register`,
            `/my-page`,
            `/@vite/client`,
            `/@fs/code/node_modules/vite/dist/client/`,
            `/@react-refresh`,
          ) ||
          PathPrefix(
            `/src/`,
            `/node_modules/`,
            `/config/`
          )
        )"
networks:
  docker_default:
    name: docker_default

volumes:
  code:
  node-modules: