version: '3.9'
services:
  web:
    container_name: new-world-front-web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    networks:
      - default
      - docker_default
    volumes:
      - ./dist:/code/dist
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.new-world-front.loadbalancer.server.port=80"
      - "traefik.http.routers.new-world-front.rule=HostRegexp(`nw.fyui001.com`) && (
          Path(
            `/`,
            `/__vite_ping`,
            `/login`,
            `/register`,
            `/my-page`,
            `/@vite/client`,
            `/@fs/code/node_modules/vite/dist/client/`,
            `/@react-refresh`,
          ) ||
          PathPrefix(
            `/assets/`,
            `/src/`,
            `/node_modules/`,
            `/config/`
          )
        )"
  app:
    container_name: new-world-app
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    volumes:
      - .:/code
      - node-modules:/code/node_modules
    stdin_open: true
    labels:
      - "traefik.enable=false"
networks:
  docker_default:
    name: docker_default

volumes:
  node-modules: