version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - default
      - docker_default
    volumes:
      - .:/code
      - node-modules:/code/node_modules
    stdin_open: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.new-world-front.loadbalancer.server.port=8080"
      - "traefik.http.routers.new-world-front.rule=HostRegexp(`nw.localhost`) && (
          Path(
            `/`,
            `/login`,
            `/register`,
            `/my-page`
          )
        )"

networks:
  docker_default:
    name: docker_default

volumes:
  node-modules: